export const CUPOM_REGISTER_REQUEST = 'CUPOM_REGISTER_REQUEST';
export const CUPOM_REGISTER_SUCCESS = 'CUPOM_REGISTER_SUCCESS';
export const CUPOM_REGISTER_FAIL = 'CUPOM_REGISTER_FAIL';

export const CUPOM_LIST_REQUEST = 'CUPOM_LIST_REQUEST';
export const CUPOM_LIST_SUCCESS = 'CUPOM_LIST_SUCCESS';
export const CUPOM_LIST_FAIL = 'CUPOM_LIST_FAIL';

export const CUPOM_DETAILS_REQUEST = 'CUPOM_DETAILS_REQUEST';
export const CUPOM_DETAILS_SUCCESS = 'CUPOM_DETAILS_SUCCESS';
export const CUPOM_DETAILS_FAIL = 'CUPOM_DETAILS_FAIL';

export const CUPOM_INACTIVE_REQUEST = 'CUPOM_INACTIVE_REQUEST';
export const CUPOM_INACTIVE_SUCCESS = 'CUPOM_INACTIVE_SUCCESS';
export const CUPOM_INACTIVE_FAIL = 'CUPOM_INACTIVE_FAIL';