export const END_REGISTER_REQUEST = 'END_REGISTER_REQUEST';
export const END_REGISTER_SUCCESS = 'END_REGISTER_SUCCESS';
export const END_REGISTER_FAIL = 'END_REGISTER_FAIL';

export const END_REQUEST = 'END_REQUEST';
export const END_REQUEST_SUCESS = 'END_REQUEST_SUCESS';
export const END_REQUEST_FAIL = 'END_REQUEST_FAIL';

export const END_DETAILS_REQUEST = 'END_DETAILS_REQUEST';
export const END_DETAILS_SUCCESS = 'END_DETAILS_SUCCESS';
export const END_DETAILS_FAIL = 'END_DETAILS_FAIL';

export const END_UPDATE_REQUEST = 'END_UPDATE_REQUEST';
export const END_UPDATE_SUCCESS = 'END_UPDATE_SUCCESS';
export const END_UPDATE_FAIL = 'END_UPDATE_FAIL';

export const END_REMOVE_REQUEST = 'END_REMOVE_REQUEST';
export const END_REMOVE_SUCCESS = 'END_REMOVE_SUCCESS';
export const END_REMOVE_FAIL = 'END_REMOVE_FAIL';