export const PAYCARD_REGISTER_REQUEST = 'PAYCARD_REGISTER_REQUEST';
export const PAYCARD_REGISTER_SUCCESS = 'PAYCARD_REGISTER_SUCCESS';
export const PAYCARD_REGISTER_FAIL = 'PAYCARD_REGISTER_FAIL';

export const PAYCARD_LIST_REQUEST = 'PAYCARD_LIST_REQUEST';
export const PAYCARD_LIST_SUCCESS = 'PAYCARD_LIST_SUCCESS';
export const PAYCARD_LIST_FAIL = 'PAYCARD_LIST_FAIL';

export const PAYCARD_DETAILS_REQUEST = 'PAYCARD_DETAILS_REQUEST';
export const PAYCARD_DETAILS_SUCCESS = 'PAYCARD_DETAILS_SUCCESS';
export const PAYCARD_DETAILS_FAIL = 'PAYCARD_DETAILS_FAIL';

export const PAYCARD_REMOVE_REQUEST = 'PAYCARD_REMOVE_REQUEST';
export const PAYCARD_REMOVE_SUCCESS = 'PAYCARD_REMOVE_SUCCESS';
export const PAYCARD_REMOVE_FAIL = 'PAYCARD_REMOVE_FAIL';